apiVersion: registry.lookout.dev/v1alpha1
kind: ImageRegistry
metadata:
  labels:
    app.kubernetes.io/name: lookout
    app.kubernetes.io/managed-by: kustomize
  name: imageregistry-sample
spec:
  # TODO(user): Add fields here
